import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/Footer";
import AppNavbar from "@/Components/AppNavbar";
import { Toaster } from "react-hot-toast";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Digital Life Lessons",
  description: "Generated by Arafat",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark light`}
      // data-theme="dark"
      data-theme="light"
    >
      <body className="min-h-full flex flex-col">
        <AppNavbar></AppNavbar>
        <main>{children}</main>
        <Footer></Footer>
        <Toaster />
        {/* <ToastContainer /> */}
      </body>
    </html>
  );
}
